# Generated by Django 2.2.2 on 2019-06-30 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorboard', '0003_auto_20190630_0453'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorapply',
            name='tutor_category',
            field=models.CharField(choices=[('디자인', '디자인'), ('뷰티', '뷰티'), ('영상', '영상'), ('외국어', '외국어'), ('음악', '음악'), ('스포츠', '스포츠')], default='디자인', max_length=10),
        ),
        migrations.AddField(
            model_name='tutorapply',
            name='tutor_subcategory',
            field=models.CharField(choices=[('포토샵', '포토샵'), ('일러스트레이터', '일러스트레이터'), ('메이크업', '메이크업'), ('헤어', '헤어'), ('패션', '패션'), ('프리미어', '프리미어'), ('에프터이펙트', '에프터이펙트'), ('파이널컷', '파이널컷'), ('영어', '영어'), ('중국어', '중국어'), ('일본어', '일본어'), ('불어', '불어'), ('독일어', '독일어'), ('보컬', '보컬'), ('피아노', '피아노'), ('성악', '성악'), ('바이올린', '바이올린'), ('플룻', '플룻'), ('빙구', '빙구'), ('족구', '족구'), ('축구', '축구'), ('테니스', '테니스'), ('스키', '스키')], default='포토샵', max_length=10),
        ),
        migrations.AddField(
            model_name='tutorrequest',
            name='tutor_category',
            field=models.CharField(choices=[('디자인', '디자인'), ('뷰티', '뷰티'), ('영상', '영상'), ('외국어', '외국어'), ('음악', '음악'), ('스포츠', '스포츠')], default='디자인', max_length=10),
        ),
        migrations.AddField(
            model_name='tutorrequest',
            name='tutor_subcategory',
            field=models.CharField(choices=[('포토샵', '포토샵'), ('일러스트레이터', '일러스트레이터'), ('메이크업', '메이크업'), ('헤어', '헤어'), ('패션', '패션'), ('프리미어', '프리미어'), ('에프터이펙트', '에프터이펙트'), ('파이널컷', '파이널컷'), ('영어', '영어'), ('중국어', '중국어'), ('일본어', '일본어'), ('불어', '불어'), ('독일어', '독일어'), ('보컬', '보컬'), ('피아노', '피아노'), ('성악', '성악'), ('바이올린', '바이올린'), ('플룻', '플룻'), ('빙구', '빙구'), ('족구', '족구'), ('축구', '축구'), ('테니스', '테니스'), ('스키', '스키')], default='포토샵', max_length=10),
        ),
    ]
